### ISSUE TITLE
支持AOT编译

### ISSUE THREAD

**Issue by greengerong** [greengerong/rebirth#11]

**Comment by greengerong** [comment]
Use angular-cli tool to implement AOT without lazyload in branch: [cli-aot-without-lazyload](https://github.com/greengerong/rebirth/tree/cli-aot-without-lazyload).

**Comment by JimChenWYU** [comment]
你好，破狼，为什么aot编译没有报错，然而会卡死在一个地方？
因为等待时间实在太长了，至今没有成功过。

**Comment by greengerong** [comment]
看这个branch的aot [cli-aot-without-lazyload](https://github.com/greengerong/rebirth/tree/cli-aot-without-lazyload)。目前angular-cli在aot在lazyload下还存在问题。

**Comment by zrzs** [comment]
拉取了 cli-aot-without-lazyload分支，还是编译报错，不知道是什么原因

**Comment by greengerong** [comment]
@hippylw 什么错误？我本地没错

**Comment by zrzs** [comment]
Cannot find module 'process-nextick-args'

**Comment by greengerong** [comment]
@hippylw 获取当前的master版本看看呢。 安装angular-cli@1.0.0-beta.21

需要注释掉nodde_modules/@ngtools/webpack/src/loader.js中的_removeDecorators方法：

    function _removeDecorators(refactor) {
        // Find all decorators.
        // refactor.findAstNodes(refactor.sourceFile, ts.SyntaxKind.Decorator)
        //     .forEach(function (d) { return refactor.removeNode(d); });
    }

这会移除自定义的装饰器，在下个版本cli将被修复

**Comment by greengerong** [comment]
AOT已经在master分支支持
