### ISSUE TITLE
has no exported member 'RebirthPermissionModule'.

### ISSUE THREAD

**Issue by jay763190097** [greengerong/rebirth#14]
src/app/manage-app/manage-app.modules.ts Module '"node/modules/rebirth-permission/dist/index"' has no exported member 'RebirthPermissionModule'.

**Comment by greengerong** [comment]
This is due to RebirthPermission had upgrade. Will fix soon.

**Comment by greengerong** [comment]
fixed in commit [https://github.com/greengerong/rebirth/commit/3ffcb1379f4d6ad2f5ec18cae4eeeeed793de07a](https://github.com/greengerong/rebirth/commit/3ffcb1379f4d6ad2f5ec18cae4eeeeed793de07a)
