### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by leo19930826** [greengerong/rebirth#15]
你好，我将该项目下载下来后，按照github上的步骤进行运行，结果在开发环境上安装一直报错。由于github无法截取报错图片,因此我将报错信息copy过来，以下是报错信息：

styles.bundle.js:33Uncaught Error: Module build failed: Error: dlopen(/Users/LI/Desktop/rebirth/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:(…)696 @ styles.bundle.js:33__webpack_require__ @ bootstrap 61b1572…:52422 @ bootstrap.scss:4__webpack_require__ @ bootstrap 61b1572…:52794 @ addStyles.js:246__webpack_require__ @ bootstrap 61b1572…:52webpackJsonpCallback @ bootstrap 61b1572…:23(anonymous function) @ styles.bundle.js:1
index.js:61Uncaught Error: Module build failed: Error: dlopen(/Users/LI/Desktop/rebirth/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:(…)(anonymous function) @ index.js:61__webpack_require__ @ bootstrap 61b1572…:52(anonymous function) @ app.component.ts:9(anonymous function) @ app.component.ts:39__webpack_require__ @ bootstrap 61b1572…:52(anonymous function) @ app.component.ts:39__webpack_require__ @ bootstrap 61b1572…:52(anonymous function) @ rebirth-window.ts:50__webpack_require__ @ bootstrap 61b1572…:52(anonymous function) @ src async:22__webpack_require__ @ bootstrap 61b1572…:52(anonymous function) @ zone.js:1426__webpack_require__ @ bootstrap 61b1572…:52webpackJsonpCallback @ bootstrap 61b1572…:23(anonymous function) @ main.bundle.js:1
client?93b6:38[WDS] Errors while compiling.
client?93b6:80./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles/bootstrap.scss
Module build failed: Error: dlopen(/Users/LI/Desktop/rebirth/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/LI/Desktop/rebirth/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 86576
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

**Comment by greengerong** [comment]
你下载的那个分支？ 看报错想node-scss之类的没装上。

**Comment by JimChenWYU** [comment]
遇过，执行以下命令解决，这是一个关于node-sass的问题
`SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install node-sass --save-dev`

**Comment by greengerong** [comment]
@leo19930826  解决了吗？ 按照楼上的说法，这应该就是代理问题。设置为国内淘宝npm代理或者开启代理客户端就可以解决了。

如果没什么问题，请帮助关闭这个问题。

**Comment by greengerong** [comment]
没有回应因为关闭此问题
