### ISSUE TITLE
run project error

### ISSUE THREAD

**Issue by gatspy** [greengerong/rebirth#17]
用run project指导中的`npm run jit & npm run aot` 运行项目错误。
单独使用`npm run jit ` `npm run aot`可以成功。

**Comment by greengerong** [comment]
是的。 npm run jit 和npm run aot 是不同的两种启动服务的方式

**Comment by gatspy** [comment]
谢谢破狼，一直在用1.x。等忙完了好好研究你的这个项目。

**Comment by greengerong** [comment]
没事。欢迎使用学习。
