### ISSUE TITLE
ng2 怎么支持SEO搜索呢

### ISSUE THREAD

**Issue by wangjianan1103** [greengerong/rebirth#19]
使用google 抓取到的网站首页只是没渲染之前的index，里面一些title meta都还没有渲染上，则怎么处理呢

**Comment by Program-Monkey** [comment]
服务端渲染

**Comment by wangjianan1103** [comment]
现在再找支持服务端渲染的方法，我这边使用webpack 打包的，使用什么来实现服务端渲染呢

**Comment by greengerong** [comment]
[https://github.com/evertonrobertoauler/cli-universal-demo/tree/master/src](https://github.com/evertonrobertoauler/cli-universal-demo/tree/master/src)
